### ISSUE TITLE
[bike-shedding] Unused arity?

### ISSUE THREAD

**Issue by piotr-yuxuan** [Tyruiop/aho#1]
Thank you so much for this amazing piece of code jewelry 🤩

I've been wondering, is [this signature](https://github.com/Tyruiop/aho/blob/7774887014f350a136dfbcf17875e9047e777491/src/aho/core.cljc#L93) needed? or was it for tests / repl purpose?

**Comment by Tyruiop** [comment]
Thank you for the kind word!

Regarding the signature, I did that not to have to write the accumulating argument in a function call, mostly for readability. But it's true that given that it is only called in once place, it's probably overkill, I will change it, thanks for pointing it out.

**Comment by Tyruiop** [comment]
Solved in latest commit
